# Generated by Django 5.0.4 on 2024-04-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_published_date_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.TextField(default=1, verbose_name='Контакти'),
            preserve_default=False,
        ),
    ]
