# Generated by Django 5.0.4 on 2024-04-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_location_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
