# Generated by Django 5.0.4 on 2024-05-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_review_comment_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='published_date',
            new_name='created_at',
        ),
    ]
